### ISSUE TITLE
After sending the invitation, it should close the issue 

### ISSUE THREAD

**Issue by eddiejaoude** [vj-abigo/invite-on-label#10]
1. [x] send invitation
2. [x] add comment
3. [x] close issue

**Comment by vj-abishek** [comment]
Does anyone like to work on this?

**Comment by vj-abishek** [comment]
Hint: just need to update the state of the comment message

Like this
``` js
await client.issues.update({
  owner: payload.repository.owner.login,
  repo: payload.repository.name,
  issue_number: payload.issue.number,
  state: 'closed'
})
```
After comment message is created

Check index.js

**Comment by rohank2502** [comment]
yes i will like to contribute

**Comment by vj-abishek** [comment]
@eddiejaoude this will be released in v1.2

**Comment by vj-abishek** [comment]
Released 🎉

**Comment by eddiejaoude** [comment]
Great 👍
