### ISSUE TITLE
Invite automation not working

### ISSUE THREAD

**Issue by PulkitSinghDev** [vj-abigo/invite-on-label#16]
Hi, we tried to integrate this invite on label github workflow but it's not working since we had some trial tests

**Comment by vj-abishek** [comment]
@PulkitSinghDev sorry for the late reply. 

I didn't get your point. What do you mean by `trail tests`?
Do you got any error in the workflow? If you share those it will be more helpful 

Please elaborate your issue, I can help you in getting up and running.

**Comment by vj-abishek** [comment]
I tested your support repo, it looks like it is working.

**Comment by vj-abishek** [comment]
I think your issue is solved. So closing this issue.
