### ISSUE TITLE
Didn't worked for my Org

### ISSUE THREAD

**Issue by AnirudhPanda** [vj-abigo/invite-on-label#17]
I think I messed up somewhere after REPOSITORY SECRET
Can you please guide in detail after that step

**Comment by AnirudhPanda** [comment]
> I think I messed up somewhere after REPOSITORY SECRET
> Can you please guide in detail after that step @rohan-kulkarni-25

**Comment by vj-abishek** [comment]
Step 1: copy this example in ur repo
https://github.com/EddieHubCommunity/support/blob/main/.github/workflows/invitation.yml
And make necessary changes

Step2: go here https://github.com/settings/tokens and give admin:org scope

Step3: token will be shown when u create. Copy it(note: it just shows once so don't forget to copy it) 
Copy the generated token and navigate to your org's secrets(Organization Settings > Secrets) and create a New Organization Secret with the Name as INVITE_TOKEN and the value as the token that you copied in the previous step.

Done

If any issues, you can ask

**Comment by vj-abishek** [comment]
@AnirudhPanda sorry for the late reply 😅

**Comment by AnirudhPanda** [comment]
thanks man!
