### ISSUE TITLE
CONTRIBUTING.md does not exist

### ISSUE THREAD

**Issue by satyampgt4** [vj-abigo/invite-on-label#19]
Things should be in contributing.md file

## Local setup:
1. First `Fork the repo`
2. To clone th repo `git clone https://github.com/vj-abigo/invite-on-label.git`
3. cd `invite-on-label`
4. `npm install` ( make sure you have node js installed) 
5. Make your changes in `index.js` at the root. 
6. After when you made your necessary changes. Run `npm run build` to build the file

Docs on creating a GitHub action: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action

Docs on octokit: https://octokit.github.io/rest.js/v18

Docs for GitHub workflow: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

Docs for workflow events: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issues

If needed any additional changes,feel  free to make those!

**Comment by vj-abishek** [comment]
@satyampgt4 thanks for noting the issue. 
It really helps. 

Actually need to add CONTRIBUTING.md file

**Comment by joshi-kaushal** [comment]
I can work on this.

**Comment by satyampgt4** [comment]
> @satyampgt4 thanks for noting the issue. It really helps.
> 
> Actually need to add CONTRIBUTING.md file

i like to work on it please assign this issue to me
