### ISSUE TITLE
Add issue template (Bug & Feature)

### ISSUE THREAD

**Issue by Evavic44** [vj-abigo/invite-on-label#23]
Add issue templates to help users looking to contribute to this project.

- [x] Bug template
For errors or bugs found on the project

- [x] Feature
For adding new ideas or updates to the project.

I have a rough draft written down, if accepted I will make the required changes. 
Thanks. 🙂

**Comment by vj-abishek** [comment]
Yah, go ahead. I did like to see those changes.
